AdminPanelTest/Models/ErrorViewModel.cs
namespace AdminPanelTest.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AdminPanelTest/Models/Section1.cs
namespace AdminPanelTest.Models
{
    public class Section1
    {
        public int Id { get; set; }
        public string? Header { get; set; }
        public string? SubHeader { get; set; }

        public string? Title { get; set; }
        public string? Description { get; set; }

    }
}

AdminPanelTest/Models/TestContext.cs
using Microsoft.EntityFrameworkCore;

namespace AdminPanelTest.Models
{
    public class TestContext : DbContext
    {
        public TestContext (DbContextOptions opt) : base(opt)
        {

        }
        public DbSet<Section1> Section1ss { get; set; }

    }
}

AdminPanelTest/Areas/AdminTest/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace AdminPanelTest.Areas.AdminTest.Controllers
{
    [Area("AdminTest")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AdminPanelTest/Areas/AdminTest/Controllers/Section1Controller.cs
using AdminPanelTest.Models;
using Microsoft.AspNetCore.Mvc;

namespace AdminPanelTest.Areas.AdminTest.Controllers
{
    [Area("AdminTest")]
    public class Section1Controller : Controller
    {
        private readonly TestContext _context;

        public Section1Controller(TestContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Section1ss.FirstOrDefault());
        }
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(Section1 section1)
        {
            _context.Section1ss.Add(section1);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var section1  =_context.Section1ss.Find(id);
            return View(section1);
        }
        [HttpPost]
        public IActionResult Edit (Section1 section1)
        {

            _context.Section1ss.Update(section1);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Delete(Section1 section1,int id)
        {

            var Section1 = _context.Section1ss.Find(id);
            _context.Section1ss.Remove(section1);
            _context.SaveChanges();
            return RedirectToAction(nameof (Index));
        }

        public IActionResult Details()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            var section1 =_context.Section1ss.FirstOrDefault(x=>x.Id == id);
            return View (section1);
        }
        public IActionResult Back()
        {
            return RedirectToAction(nameof(Index));
        }
    }
}

AdminPanelTest/Controllers/HomeController.cs
using AdminPanelTest.Model_VIew;
using AdminPanelTest.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AdminPanelTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly TestContext _testContext;
        public HomeController(ILogger<HomeController> logger, TestContext context)
        {
            _logger = logger;
            _testContext = context;
        }

        public IActionResult Index()
        {
            IndexVM vm = new();
            vm.Section1 =_testContext.Section1ss.First();

            return View(vm);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AdminPanelTest/Areas/AdminTest/Views/Dashboard/Index.cshtml
@model Section1

@*Hammisi ucun a href aciruq *@
<a href = "/AdminOleev/Section1/Delete/"></a>
<h1>Xos gelmisziniz</h1>

AdminPanelTest/Areas/AdminTest/Views/Section1/Back.cshtml
@model Section1

AdminPanelTest/Areas/AdminTest/Views/Section1/Create.cshtml
@model Section1

<form method = "post">
    <lable>Headre</lable>
    <input asp-for="Header"  />
    
    <lable>Title</lable>
    <input  asp-for="Title"  />
    <lable>Title</lable>

    <input  asp-for="Description"  />
    <input value="Create" type ="submit" />



</form>

AdminPanelTest/Areas/AdminTest/Views/Section1/Delete.cshtml
@model Section1

<h1>  Section1 Table i silinsin?</h1>

<a asp-action = "index">Cancel</a>

AdminPanelTest/Areas/AdminTest/Views/Section1/Edit.cshtml
@model Section1


<form method="post">

    <lable>Headre</lable>
    <input asp-for="Header"  />

    <lable>Description</lable>
    <input  asp-for="Description"  />
    
    <lable>Subheader</lable>
    <input  asp-for="SubHeader"  />

    <lable>title</lable>

    <input  asp-for="Title"  />

    <input value="Edit" type ="submit" />

</form>
<a asp-action = "Back"> Back</a>

AdminPanelTest/Areas/AdminTest/Views/Section1/Index.cshtml
@model Section1

@{
    int count = 0;
}
@*@foreach(var item in Model){
    count ++;

    };*@

<div class="table-responsive">
    <table id="default-datatable" class="display table table-striped table-bordered">
        <thead>
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td> @Model.Header</td>
                <td>@Model.Description</td>
                <td>@Model.SubHeader</td>
                <td>@Model.Title</td>


            </tr>

    </table>
</div>
<a  asp-controller="Section1" asp-action="Create"> create</a>
<a   asp-controller="Section1" asp-action="Edit"> edit</a>
<a asp-controller="Section1" asp-action="Delete">Delete</a>

AdminPanelTest/Views/Home/Index.cshtml
@using AdminPanelTest.Model_VIew
@model IndexVM

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AdminPanelTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdminPanelTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdminPanelTest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AdminPanelTest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AdminPanelTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>